# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomerRecordSample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CustomerRecordSample.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x43ustomerRecordSample.proto\">\n\x14\x43ustomerRecordSample\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\x0f\n\x07row_num\x18\x02 \x02(\x03')
)




_CUSTOMERRECORDSAMPLE = _descriptor.Descriptor(
  name='CustomerRecordSample',
  full_name='CustomerRecordSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_name', full_name='CustomerRecordSample.customer_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row_num', full_name='CustomerRecordSample.row_num', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['CustomerRecordSample'] = _CUSTOMERRECORDSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomerRecordSample = _reflection.GeneratedProtocolMessageType('CustomerRecordSample', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERRECORDSAMPLE,
  __module__ = 'CustomerRecordSample_pb2'
  # @@protoc_insertion_point(class_scope:CustomerRecordSample)
  ))
_sym_db.RegisterMessage(CustomerRecordSample)


# @@protoc_insertion_point(module_scope)
