# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OGDFormat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OGDFormat.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fOGDFormat.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x05\n\x0e\x43ustomerRecord\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0e\n\x06\x61pp_id\x18\x02 \x02(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12/\n\tuser_data\x18\x04 \x03(\x0b\x32\x1c.CustomerRecord.NestedRecord\x12\x12\n\nsession_id\x18\x05 \x02(\t\x12\x12\n\nevent_name\x18\x06 \x02(\t\x12\x30\n\nevent_data\x18\x07 \x03(\x0b\x32\x1c.CustomerRecord.NestedRecord\x12\x30\n\ngame_state\x18\x08 \x03(\x0b\x32\x1c.CustomerRecord.NestedRecord\x12.\n\nevent_time\x18\t \x02(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\revent_time_ms\x18\n \x01(\x05\x12\x13\n\x0btime_offset\x18\x0b \x01(\x05\x12\x13\n\x0b\x61pp_version\x18\x0c \x02(\t\x12\x12\n\napp_branch\x18\r \x01(\t\x12\x13\n\x0blog_version\x18\x0e \x02(\x05\x12\x17\n\x0fhttp_user_agent\x18\x0f \x01(\t\x12\x13\n\x0bremote_addr\x18\x10 \x01(\t\x12\x1c\n\x14\x65vent_sequence_index\x18\x11 \x02(\x03\x1a\x9f\x01\n\x0cNestedRecord\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.CustomerRecord.NestedRecord.ValueKinds\x1aJ\n\nValueKinds\x12\x14\n\x0cstring_value\x18\x01 \x01(\t\x12\x11\n\tint_value\x18\x02 \x01(\x03\x12\x13\n\x0b\x66loat_value\x18\x03 \x01(\x02')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CUSTOMERRECORD_NESTEDRECORD_VALUEKINDS = _descriptor.Descriptor(
  name='ValueKinds',
  full_name='CustomerRecord.NestedRecord.ValueKinds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_value', full_name='CustomerRecord.NestedRecord.ValueKinds.string_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='CustomerRecord.NestedRecord.ValueKinds.int_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='CustomerRecord.NestedRecord.ValueKinds.float_value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=695,
)

_CUSTOMERRECORD_NESTEDRECORD = _descriptor.Descriptor(
  name='NestedRecord',
  full_name='CustomerRecord.NestedRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CustomerRecord.NestedRecord.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CustomerRecord.NestedRecord.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMERRECORD_NESTEDRECORD_VALUEKINDS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=695,
)

_CUSTOMERRECORD = _descriptor.Descriptor(
  name='CustomerRecord',
  full_name='CustomerRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CustomerRecord.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_id', full_name='CustomerRecord.app_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='CustomerRecord.user_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_data', full_name='CustomerRecord.user_data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='CustomerRecord.session_id', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_name', full_name='CustomerRecord.event_name', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_data', full_name='CustomerRecord.event_data', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_state', full_name='CustomerRecord.game_state', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_time', full_name='CustomerRecord.event_time', index=8,
      number=9, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_time_ms', full_name='CustomerRecord.event_time_ms', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_offset', full_name='CustomerRecord.time_offset', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_version', full_name='CustomerRecord.app_version', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_branch', full_name='CustomerRecord.app_branch', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_version', full_name='CustomerRecord.log_version', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='http_user_agent', full_name='CustomerRecord.http_user_agent', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote_addr', full_name='CustomerRecord.remote_addr', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_sequence_index', full_name='CustomerRecord.event_sequence_index', index=16,
      number=17, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMERRECORD_NESTEDRECORD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=695,
)

_CUSTOMERRECORD_NESTEDRECORD_VALUEKINDS.containing_type = _CUSTOMERRECORD_NESTEDRECORD
_CUSTOMERRECORD_NESTEDRECORD.fields_by_name['value'].message_type = _CUSTOMERRECORD_NESTEDRECORD_VALUEKINDS
_CUSTOMERRECORD_NESTEDRECORD.containing_type = _CUSTOMERRECORD
_CUSTOMERRECORD.fields_by_name['user_data'].message_type = _CUSTOMERRECORD_NESTEDRECORD
_CUSTOMERRECORD.fields_by_name['event_data'].message_type = _CUSTOMERRECORD_NESTEDRECORD
_CUSTOMERRECORD.fields_by_name['game_state'].message_type = _CUSTOMERRECORD_NESTEDRECORD
_CUSTOMERRECORD.fields_by_name['event_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['CustomerRecord'] = _CUSTOMERRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomerRecord = _reflection.GeneratedProtocolMessageType('CustomerRecord', (_message.Message,), dict(

  NestedRecord = _reflection.GeneratedProtocolMessageType('NestedRecord', (_message.Message,), dict(

    ValueKinds = _reflection.GeneratedProtocolMessageType('ValueKinds', (_message.Message,), dict(
      DESCRIPTOR = _CUSTOMERRECORD_NESTEDRECORD_VALUEKINDS,
      __module__ = 'OGDFormat_pb2'
      # @@protoc_insertion_point(class_scope:CustomerRecord.NestedRecord.ValueKinds)
      ))
    ,
    DESCRIPTOR = _CUSTOMERRECORD_NESTEDRECORD,
    __module__ = 'OGDFormat_pb2'
    # @@protoc_insertion_point(class_scope:CustomerRecord.NestedRecord)
    ))
  ,
  DESCRIPTOR = _CUSTOMERRECORD,
  __module__ = 'OGDFormat_pb2'
  # @@protoc_insertion_point(class_scope:CustomerRecord)
  ))
_sym_db.RegisterMessage(CustomerRecord)
_sym_db.RegisterMessage(CustomerRecord.NestedRecord)
_sym_db.RegisterMessage(CustomerRecord.NestedRecord.ValueKinds)


# @@protoc_insertion_point(module_scope)
